### ISSUE TITLE
rtabmap_viz segfaults a few seconds after starting (Ubuntu 24.04, raspberry pi 5, realsense D435)

### ISSUE THREAD

**Issue by carljones3000** [introlab/rtabmap_ros#1230]
Hello, my issue is that the launch runs for a few seconds and then it segfaults. It happens every time. (Note: it is working in terms of building a map until it crashes with the segfault.)

Any help is appreciated

Raspberry Pi 5
Ubuntu 24.04.1 LTS

camera: realsense D435, firmware 5.16.01

installation:
ros-jazzy-rtabmap-conversions/noble,now 0.21.5-3noble.20240922.134320 arm64 [installed,automatic]
ros-jazzy-rtabmap-demos/noble,now 0.21.5-3noble.20240923.070707 arm64 [installed,automatic]
ros-jazzy-rtabmap-examples/noble,now 0.21.5-3noble.20241003.151341 arm64 [installed,automatic]
ros-jazzy-rtabmap-launch/noble,now 0.21.5-3noble.20240923.070702 arm64 [installed,automatic]
ros-jazzy-rtabmap-msgs/noble,now 0.21.5-3noble.20240922.082858 arm64 [installed,automatic]
ros-jazzy-rtabmap-odom/noble,now 0.21.5-3noble.20240923.065043 arm64 [installed,automatic]
ros-jazzy-rtabmap-python/noble,now 0.21.5-3noble.20240705.172114 arm64 [installed,automatic]
ros-jazzy-rtabmap-ros/noble,now 0.21.5-3noble.20241003.151618 arm64 [installed]
ros-jazzy-rtabmap-rviz-plugins/noble,now 0.21.5-3noble.20240922.135254 arm64 [installed,automatic]
ros-jazzy-rtabmap-slam/noble,now 0.21.5-3noble.20240923.065043 arm64 [installed,automatic]
ros-jazzy-rtabmap-sync/noble,now 0.21.5-3noble.20240923.061517 arm64 [installed,automatic]
ros-jazzy-rtabmap-util/noble,now 0.21.5-3noble.20240922.135253 arm64 [installed,automatic]
ros-jazzy-rtabmap-viz/noble,now 0.21.5-3noble.20240923.065042 arm64 [installed,automatic]
ros-jazzy-rtabmap/noble,now 0.21.6-1noble.20240922.121905 arm64 [installed,automatic]

command used to start it:
ros2 launch rtabmap_examples realsense_d400_custom.launch.py

launch file
[realsense_d400_custom.launch.py.txt](https://github.com/user-attachments/files/17529820/realsense_d400_custom.launch.py.txt)

Output from the run with debugger:
[New Thread 0xffff927f7040 (LWP 10871)]                                         
[Thread 0xffff91df7040 (LWP 10870) exited]                                      
[Thread 0xffff927f7040 (LWP 10871) exited]                                      
[New Thread 0xffff927f7040 (LWP 10872)]                                         
[Thread 0xffff927f7040 (LWP 10872) exited]                                      
[New Thread 0xffff927f7040 (LWP 10873)]                                         
[Thread 0xffff927f7040 (LWP 10873) exited]                                      
[New Thread 0xffff927f7040 (LWP 10874)]                                         
[Thread 0xffff927f7040 (LWP 10874) exited]                                      
[ WARN] (2024-10-26 09:24:07.628) util3d.cpp:488::cloudFromDepthRGB() Decimation������������������������������������������������������������               (4) is not valid for current image size (depth=480x270). Highest compatible dec������������������������������������������������������������              imation used=3.                                                                 ������������                      
[ WARN] (2024-10-26 09:24:07.957) util3d.cpp:488::cloudFromDepthRGB() Decimation������������������������������������������������������������               (4) is not valid for current image size (depth=480x270). Highest compatible dec������������������������������������������������������������              imation used=3.                                                                 ������������                      
[ WARN] (2024-10-26 09:24:08.080) util3d.cpp:488::cloudFromDepthRGB() Decimation������������������������������������������������������������               (4) is not valid for current image size (depth=480x270). Highest compatible dec������������������������������������������������������������              imation used=3.                                                                 ������������                      
[ WARN] (2024-10-26 09:24:08.214) util3d.cpp:488::cloudFromDepthRGB() Decimation������������������������������������������������������������               (4) is not valid for current image size (depth=480x270). Highest compatible dec������������������������������������������������������������              imation used=3.                                                                 ������������                      
[Thread 0xffffa9ff7040 (LWP 10838) exited]                                      
[Thread 0xffffa95f7040 (LWP 10839) exited]                                      
[Thread 0xffffa8bf7040 (LWP 10840) exited]                                      
[Thread 0xffff9fdf7040 (LWP 10841) exited]                                      

Thread 1 "rtabmap_viz" received signal SIGSEGV, Segmentation fault.             
0x0000000000000000 in ?? ()                                                     ������������������������                    
(gdb) backtrace                                                                 
#0  0x0000000000000000 in ??? ()                                                                
#1  0x0000fffff2b19a20 in vtkOpenGLRenderTimer::ReusableStart                                   
    (this=0xaaaaadbb1020)                                                       
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpen          GLRenderTimer.cxx:302                                                           ������������������2                    
#2  0x0000fffff2af6088 in vtkOpenGLPolyDataMapper::RenderPieceStart             �����               
    (this=0xaaaaadb8c070, ren=0xaaaaadb67ad0, actor=0xaaaaadb826d0)                                                         
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpen                                                GLPolyDataMapper.cxx:3387
#3  0x0000fffff2b0debc in vtkOpenGLPolyDataMapper::RenderPiece
    (this=0xaaaaadb8c070, ren=0xaaaaadb67ad0, actor=0xaaaaadb826d0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpenGLPolyDataMapper.cxx:3609
#4  0x0000fffff2727168 in vtkPolyDataMapper::Render
    (this=0xaaaaadb8c070, ren=0xaaaaadb67ad0, act=0xaaaaadb826d0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkPolyDataMapper.cxx:65
#5  0x0000fffff2ab75a0 in vtkOpenGLActor::Render
    (this=0xaaaaadb826d0, ren=0xaaaaadb67ad0, mapper=0xaaaaadb8c070)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpenGLActor.cxx:104
#6  0x0000fffff3dc5c4c in vtkLODActor::Render
    (this=0xaaaaad7aefd0, ren=0xaaaaadb67ad0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/LOD/vtkLODActor.cxx:188
#7  0x0000fffff269b1d4 in vtkActor::RenderOpaqueGeometry
    (this=0xaaaaad7aefd0, vp=0xaaaaadb67ad0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkActor.cxx:230
#8  0x0000fffff274472c in vtkRenderer::UpdateOpaquePolygonalGeometry
    (this=0xaaaaadb67ad0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkRenderer.cxx:741
#9  0x0000fffff2b29cbc in vtkOpenGLRenderer::UpdateGeometry
    (this=0xaaaaadb67ad0, fbo=0x0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpenGLRenderer.cxx:393
#10 0x0000fffff2b2bc4c in vtkOpenGLRenderer::DeviceRender (this=0xaaaaadb67ad0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpenGLRenderer.cxx:298
#11 0x0000fffff2747a80 in vtkRenderer::Render (this=0xaaaaadb67ad0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkRenderer.cxx:382
#12 0x0000fffff274dd64 in vtkRendererCollection::Render (this=0xaaaaad7cc870)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkRendererCollection.cxx:51
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x0000fffff2738e34 in vtkRenderWindow::DoStereoRender (this=0xaaaaad7acbc0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkRenderWindow.cxx:344
#14 0x0000fffff27393e4 in vtkRenderWindow::Render
    (this=this@entry=0xaaaaad7acbc0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/Core/vtkRenderWindow.cxx:304
#15 0x0000fffff2b27340 in vtkOpenGLRenderWindow::Render
    (this=this@entry=0xaaaaad7acbc0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx:2333
#16 0x0000fffff2ab2428 in vtkGenericOpenGLRenderWindow::Render
    (this=0xaaaaad7acbc0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkGenericOpenGLRenderWindow.cxx:222
#17 vtkGenericOpenGLRenderWindow::Render (this=0xaaaaad7acbc0)
    at /usr/src/vtk9-9.1.0+really9.1.0+dfsg2-7.1build3/Rendering/OpenGL2/vtkGenericOpenGLRenderWindow.cxx:201
#18 0x0000fffff6cc1ad0 in rtabmap::MainWindow::processOdometry(rtabmap::OdometryEvent const&, bool) ()
    at /opt/ros/jazzy/lib/aarch64-linux-gnu/librtabmap_gui.so.0.21
#19 0x0000fffff4d02b00 in QObject::event
    (this=0xaaaaad0d1860, e=0xffff340012b0) at kernel/qobject.cpp:1347
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x0000fffff5162aa8 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0xaaaaad0d1860, e=0xffff340012b0)
    at kernel/qapplication.cpp:3640
#21 0x0000fffff4ccc480 in QCoreApplication::notifyInternal2 (receiver=0xaaaaad0d1860, event=0xffff340012b0)
    at kernel/qcoreapplication.cpp:1064
#22 0x0000fffff4ccc76c in QCoreApplication::sendEvent (receiver=receiver@entry=0xaaaaad0d1860, event=event@entry=0xffff340012b0)
    at kernel/qcoreapplication.cpp:1462
#23 0x0000fffff4cd0340 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0xaaaaab49e220)
    at kernel/qcoreapplication.cpp:1821
#24 0x0000fffff4cd0a4c in QCoreApplication::sendPostedEvents (receiver=<optimized out>, event_type=<optimized out>)
    at kernel/qcoreapplication.cpp:1680
#25 0x0000fffff4d3880c in postEventSourceDispatch (s=0xaaaaab7a0500) at kernel/qeventdispatcher_glib.cpp:277
#26 0x0000ffffea0df89c in g_main_dispatch (context=0xffffc4000ed0) at ../../../glib/gmain.c:3344
#27 0x0000ffffea142998 in g_main_context_dispatch_unlocked (context=0xffffc4000ed0) at ../../../glib/gmain.c:4152
#28 g_main_context_iterate_unlocked.isra.0
    (context=context@entry=0xffffc4000ed0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4217
#29 0x0000ffffea0deb58 in g_main_context_iteration (context=0xffffc4000ed0, may_block=1) at ../../../glib/gmain.c:4282
#30 0x0000fffff4d37cac in QEventDispatcherGlib::processEvents (this=0xaaaaab753d50, flags=...)
    at kernel/qeventdispatcher_glib.cpp:425
#31 0x0000fffff4cca634 in QEventLoop::exec (this=this@entry=0xffffffffd020, flags=..., flags@entry=...)
    at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#32 0x0000fffff4cd45b0 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#33 0x0000aaaaaab803bc in main ()

**Comment by matlabbe** [comment]
see https://github.com/introlab/rtabmap/issues/1062#issuecomment-1597997914
